//
//  LoginViewController.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
    func displayBiometricButton(viewModel: Login.Biometric.CheckBiometricModes.ViewModel)
    func handleBiometricAuth(viewModel: Login.ApiAuthentication.ViewModel)
    func handleLoginResponse(viewModel: Login.ApiAuthentication.ViewModel)
    func handleStoredCredential(_ viewModel: Login.KeyChain.ViewModel)

}

class LoginViewController: UIViewController, UIPickerViewDelegate, UIPickerViewDataSource,LoginDisplayLogic
{
  var interactor: LoginBiometricLogic?
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: IBOutlets
    @IBOutlet weak var userNameTF: UITextField!
    @IBOutlet weak var passwordTF: UITextField!
    @IBOutlet weak var progressActivity: UIActivityIndicatorView!
    @IBOutlet weak var rememberMeSwitch: UISwitch!
    @IBOutlet var languagePicker: UIPickerView!
    
    @IBOutlet weak var languagePickerTextField: UITextField!
    @IBOutlet weak var biometricAuthBtn: UIButton!
    
  // MARK: IBActions
    @IBAction func loginClicked(_ sender: Any) {
        self.view.endEditing(true)
        self.resignFirstResponder()
        doLogin()
    }
    
    @IBAction func rememberMeValueChanged(_ sender: Any) {
        UserDefaults.standard.set(rememberMeSwitch.isOn, forKey: ConstantKeys.rememberMe.rawValue)
    }
    
    @IBAction func forgotPassClicked(_ sender: Any) {
    }
    
    
    @IBAction func biometricAuthBtnClicked(_ sender: Any) {
        let isEnrolled = UserDefaults.standard.bool(forKey: ConstantKeys.biometricLoginEnabled.rawValue)
        if isEnrolled {
            interactor?.performBiometricAuth(request: Login.ApiAuthentication.Request(  username: "", password: "", isSaveCredential: true, isFirstTimeUser: false, loginMode: .biometric))
            }else{
                enrollBiometric()
            }
        
    }
    
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    let langCultureCode: String = "es"
    let defaults = UserDefaults.standard
    defaults.set([langCultureCode], forKey: "AppleLanguages")
    defaults.synchronize()
    self.hideKeyboardWhenTappedAround()
    languagePickerTextField.inputView = languagePicker
    checkForDeviceBiometricCapabilities()
    checkForRememberMeOption()
  }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }

  // MARK: Interactor interaction
  
  
  private func checkForDeviceBiometricCapabilities()
  {
    let request = Login.Biometric.CheckBiometricModes.Request()
    interactor?.checkForDeviceBiometricCapabilities(request: request)
  }
    
   private func checkForRememberMeOption()
    {
        if let rememberMe = UserDefaults.standard.value(forKey: ConstantKeys.rememberMe.rawValue)
        {
            rememberMeSwitch.isOn = rememberMe as! Bool
            if(rememberMeSwitch.isOn)
            {
                getStoredCredential()
            }
        }
       else
       {
        rememberMeSwitch.isOn = false
        }
        
    }
    
   private func getStoredCredential()
    {
        interactor?.getStoredCredential(Login.KeyChain.Request())
    }

    
    private func enrollBiometric(){
        if let username = userNameTF.text, let password = passwordTF.text  {
            if !validateCredential(username, password){
                showAlert(title: "Alert".localized, message: "Please enter valid username and password to enroll for biometric authentication".localized)
                return
            }
            let request = Login.ApiAuthentication.Request( username: username, password: password,isSaveCredential: true, isFirstTimeUser: true, loginMode: .biometric )
            interactor?.performBiometricAuth(request: request)
            
        } else {
            showAlert(title: "Alert".localized, message: "Please enter valid username and password to enroll for biometric authentication".localized)
        }
        
    }
    
    private func doLogin() {
        if let username = userNameTF.text, let password = passwordTF.text  {
            //            self.progressActivity.startAnimating()
            let request = Login.ApiAuthentication.Request(username: username, password: password, isSaveCredential: rememberMeSwitch.isOn, isFirstTimeUser: false, loginMode: .plain)
            interactor?.performApiAuth(request: request)
            
        } else {
            showAlert(title: "Alert".localized, message: "Please enter valid username and password".localized)
        }
    }

    // MARK: Conforming Presenter
    
    func displayBiometricButton(viewModel: Login.Biometric.CheckBiometricModes.ViewModel)
    {
        if !viewModel.isBiometricVisible{
            biometricAuthBtn.isHidden = true
        }else{
            biometricAuthBtn.isHidden = false
            biometricAuthBtn.setTitle(viewModel.statusMsg.localized, for: .normal)
        }
        
    }
    
    func handleBiometricAuth(viewModel: Login.ApiAuthentication.ViewModel){
        showAlert(title: (viewModel.success ?"Success" : "failed"), message: viewModel.errorMsg)
        
    }

    func handleLoginResponse(viewModel: Login.ApiAuthentication.ViewModel)
    {
        if !viewModel.success {
            showAlert(title: "Alert".localized, message: viewModel.errorMsg)
        }
        else{
            router?.routeToDashboard(segue: nil)
        }
        
    }
    
    func handleStoredCredential(_ viewModel: Login.KeyChain.ViewModel)
    {
        userNameTF.text = viewModel.username
        passwordTF.text = viewModel.password
    }
    
    // MARK: Error handling
    
    private func showAlert(title: String, message: String)
    {
        let alertController = UIAlertController(title: title.localized, message: message.localized, preferredStyle: .alert)
        let alertAction = UIAlertAction(title: "OK".localized, style: .default, handler: nil)
        alertController.addAction(alertAction)
        showDetailViewController(alertController, sender: nil)
    }
    
    private func validateCredential(_ username: String, _ password: String) -> Bool{
        if (username.count == 0 || password.count == 0){
            return false
        }
        return true
    }

    
    // MARK: Picker DataSource & Delegate
    
    func numberOfComponents(in pickerView: UIPickerView) -> Int
    {
        return 1
    }
  
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int
    {
        return K.languageArray.count
    }
    
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String?
    {
        return K.languageArray[row][ConstantKeys.languageName.rawValue]
    }
    
    
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int)
    {
        languagePickerTextField.text = K.languageArray[row][ConstantKeys.languageName.rawValue]
    }

}


extension UIViewController {
    func hideKeyboardWhenTappedAround() {
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(UIViewController.dismissKeyboard))
        tap.cancelsTouchesInView = false
        view.addGestureRecognizer(tap)
    }
    
    @objc func dismissKeyboard() {
        view.endEditing(true)
    }
}
