//
//  LoginRouter.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToDashboard(segue: UIStoryboardSegue?)
  func routeToForgotPassword(segue: UIStoryboardSegue?)
  func routeToTFA(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToDashboard(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! DashboardViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToDashboard(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "UserFlow", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "DashboardViewController") as! DashboardViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToDashboard(source: dataStore!, destination: &destinationDS)
      navigateToDashboard(source: viewController!, destination: destinationVC)
    }
  }
    
  func routeToForgotPassword(segue: UIStoryboardSegue?)
  {
        //  if let segue = segue {
        //    let destinationVC = segue.destination as! SomewhereViewController
        //    var destinationDS = destinationVC.router!.dataStore!
        //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        //  } else {
        //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
        //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
        //    var destinationDS = destinationVC.router!.dataStore!
        //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        //    navigateToSomewhere(source: viewController!, destination: destinationVC)
        //  }
    
    }
    
    func routeToTFA(segue: UIStoryboardSegue?)
    {
        //  if let segue = segue {
        //    let destinationVC = segue.destination as! SomewhereViewController
        //    var destinationDS = destinationVC.router!.dataStore!
        //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        //  } else {
        //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
        //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
        //    var destinationDS = destinationVC.router!.dataStore!
        //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        //    navigateToSomewhere(source: viewController!, destination: destinationVC)
        //  }
    }

  // MARK: Navigation
  
    func navigateToDashboard(source: LoginViewController, destination: DashboardViewController)
    {
    source.show(destination, sender: nil)
    }
    
    func navigateToForgotPassword(source: LoginViewController, destination: DashboardViewController)
    {
        source.show(destination, sender: nil)
    }

    
    func navigateToFTA(source: LoginViewController, destination: DashboardViewController)
    {
        source.show(destination, sender: nil)
    }

  
  // MARK: Passing data
  
  func passDataToDashboard(source: LoginDataStore, destination: inout DashboardDataStore)
  {
//    destination.name = source.name
  }
    
}
