//
//  LoginModels.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ReqMode {
    case checkCapability
    case fingerAuth
    case faceAuth
}

enum AvailableBiometricMode{
    case none
    case touchId
    case faceId
}

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
    
enum Biometric
{
    enum CheckBiometricModes
    {
        struct Request
        {
        }
        
        struct Response
        {
            var avilableMode :AvailableBiometricMode
        }
        
        struct ViewModel
        {
            var avilableMode :AvailableBiometricMode

        }
    }
    
    enum Authentication
    {
        struct Request {
            var authMode :AvailableBiometricMode
        }
        struct Response {
            var success : Bool
            var errorMsg : String
        }
        
        struct ViewModel {
            var success : Bool
            var errorMsg : String
        }
    }
   
}
}
