//
//  LoginModels.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ReqMode {
    case checkCapability
    case fingerAuth
    case faceAuth
}

enum AvailableBiometricMode{
    case none
    case touchId
    case faceId
}

enum LoginMode{
    case plain
    case biometric
}

enum Login
{
  // MARK: Use cases
  
  enum ApiAuthentication
  {
    struct Request
    {
        var username: String
        var password: String
        var isSaveCredential : Bool
        var isFirstTimeUser : Bool
        var loginMode : LoginMode
    }
    struct Response {
        var success : Bool
        var errorMsg : String
    }
    
    struct ViewModel {
        var success : Bool
        var errorMsg : String
    }
  }
    
enum Biometric
{
    enum CheckBiometricModes
    {
        struct Request
        {
        }
        
        struct Response
        {
            var avilableMode :AvailableBiometricMode
            var isEnrolled: Bool
        }
        
        struct ViewModel
        {
            var isBiometricVisible :Bool
            var statusMsg : String

        }
    }
    
//    enum Authentication
//    {
//        struct Request {
//            var authMode :AvailableBiometricMode
//            var isFirstTimeUser : Bool
//            var username: String
//            var password: String
//        }
//        struct Response {
//            var success : Bool
//            var errorMsg : String
//        }
//        
//        struct ViewModel {
//            var success : Bool
//            var errorMsg : String
//        }
//    }
   
}
    enum KeyChain{
        struct Request {
            
        }
        struct Response {
            var username: String
            var password : String

        }
        struct ViewModel {
            var username: String
            var password : String
        }
    }
}
