//
//  LoginPresenter.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentBiometricBtn(response: Login.Biometric.CheckBiometricModes.Response)
    func presentBiometricAuth(response: Login.Biometric.Authentication.Response)

}

class LoginPresenter: LoginPresentationLogic
{
   
    
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
 
    
    func presentBiometricBtn(response: Login.Biometric.CheckBiometricModes.Response)
    {
        let viewModel = Login.Biometric.CheckBiometricModes.ViewModel(avilableMode: response.avilableMode)
        viewController?.displayBiometricButton(viewModel: viewModel)

    }
    
    func presentBiometricAuth(response: Login.Biometric.Authentication.Response) {
        viewController?.handleBiometricAuth(viewModel: Login.Biometric.Authentication.ViewModel(success: response.success, errorMsg: response.errorMsg))
    }
}
