//
//  LoginInteractor.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBiometricLogic
{
  func checkForDeviceBiometricCapabilities(request: Login.Biometric.CheckBiometricModes.Request)
    func performBiometricAuth(request: Login.Biometric.Authentication.Request)

}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBiometricLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func checkForDeviceBiometricCapabilities(request: Login.Biometric.CheckBiometricModes.Request )
  {
    worker = LoginWorker()
    worker?.doSomeWork()
    
    let mode = BiometricAuthWorker.sharedInstance.checkAvailableBiometricMode()
    let response = Login.Biometric.CheckBiometricModes.Response(avilableMode: mode)
    presenter?.presentBiometricBtn(response: response)
  }
    
    func performBiometricAuth(request: Login.Biometric.Authentication.Request)
    {
        
    }
    

}
