//
//  LoginViewController.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
  func displayBiometricButton(viewModel: Login.Biometric.CheckBiometricModes.ViewModel)
    func handleBiometricAuth(viewModel: Login.Biometric.Authentication.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
  var interactor: LoginBiometricLogic?
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: IBOutlets
    @IBOutlet weak var userNameTF: UITextField!
    @IBOutlet weak var passwordTF: UITextField!
    
    @IBOutlet weak var biometricAuthBtn: UIButton!
    
  // MARK: IBActions
    @IBAction func loginClicked(_ sender: Any) {
    }
    
    @IBAction func forgotPassClicked(_ sender: Any) {
    }
    
    
    @IBAction func biometricAuthBtnClicked(_ sender: Any) {
        interactor?.performBiometricAuth(request: Login.Biometric.Authentication.Request(authMode: .touchId))
    }
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    let langCultureCode: String = "es"
    let defaults = UserDefaults.standard
    defaults.set([langCultureCode], forKey: "AppleLanguages")
    defaults.synchronize()
    checkForDeviceBiometricCapabilities()
  }
    
    override func viewWillAppear(_ animated: Bool) {
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func checkForDeviceBiometricCapabilities()
  {
    let request = Login.Biometric.CheckBiometricModes.Request()
    interactor?.checkForDeviceBiometricCapabilities(request: request)
  }
  
    func displayBiometricButton(viewModel: Login.Biometric.CheckBiometricModes.ViewModel)
  {
    //nameTextField.text = viewModel.name
    switch viewModel.avilableMode {
    case .none:
        biometricAuthBtn.isHidden = true
    case .touchId:
        biometricAuthBtn.isHidden = false
        biometricAuthBtn.setTitle("Touch ID".localized, for: .normal)
    case .faceId:
        biometricAuthBtn.isHidden = false
        biometricAuthBtn.setTitle("FaceID".localized, for: .normal)


    }
  }
    
    func handleBiometricAuth(viewModel: Login.Biometric.Authentication.ViewModel){
        let alert = UIAlertController(title: (viewModel.success ?"Success" : "failed"), message: viewModel.errorMsg, preferredStyle: UIAlertController.Style.alert)
        alert.addAction(UIAlertAction(title: "Click", style: UIAlertAction.Style.default, handler: nil))
        self.present(alert, animated: true, completion: nil)

    }

}
