//
//  LoginPresenter.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 22/07/19.
//  Copyright (c) 2019 Anshu Sharma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentBiometricBtn(response: Login.Biometric.CheckBiometricModes.Response)
    func presentBiometricAuth(response: Login.ApiAuthentication.Response)
    func presentApiAuth(response: Login.ApiAuthentication.Response)
    func presentSavedCredential(_ response: Login.KeyChain.Response)


}

class LoginPresenter: LoginPresentationLogic
{
   
    
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
 
    
    func presentBiometricBtn(response: Login.Biometric.CheckBiometricModes.Response)
    {
        var isBiometricVisible = true
        var statusMsg = ""
        switch response.avilableMode {
        case .none:
             isBiometricVisible = false
             statusMsg = ""
        case .touchId:
            statusMsg = "Touch Id"
        case  .faceId:
            statusMsg = "Face Id"
        }
        if !response.isEnrolled {statusMsg = "Enroll for " + statusMsg}
        let viewModel = Login.Biometric.CheckBiometricModes.ViewModel(isBiometricVisible: isBiometricVisible, statusMsg: statusMsg)
        viewController?.displayBiometricButton(viewModel: viewModel)

    }
    
    func presentBiometricAuth(response: Login.ApiAuthentication.Response) {
        viewController?.handleBiometricAuth(viewModel: Login.ApiAuthentication.ViewModel(success: response.success, errorMsg: response.errorMsg))
    }
    
    func presentApiAuth(response: Login.ApiAuthentication.Response)
    {
        let viewModel = Login.ApiAuthentication.ViewModel(success: response.success, errorMsg: response.errorMsg)
        viewController?.handleLoginResponse(viewModel: viewModel)
    }
    
    func presentSavedCredential(_ response: Login.KeyChain.Response)
    {
        let viewModel = Login.KeyChain.ViewModel(username: response.username, password: response.password)
        viewController?.handleStoredCredential(viewModel)

    }
}
