//
//  DashboardPresenter.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 11/08/19.
//  Copyright (c) 2019 Conduent. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic
{
  func presentSomething(response: Dashboard.Something.Response)
}

class DashboardPresenter: DashboardPresentationLogic
{
  weak var viewController: DashboardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Dashboard.Something.Response)
  {
    let viewModel = Dashboard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
