# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'



target 'NJEZPass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NJEZPass

 pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'Apollo_iOS/ApolloTextInputField', :git => 'git@ssh.dev.azure.com:v3/ConduentDevOps/Innovation/Cti.Mobility.Apollo-iOS'
    pod 'SideMenu', '~> 6.0'

  target 'NJEZPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  

end

