//
//  LoginInteractor.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform

extension EditProfileInteractor: IEditProfileInteractable {
    func updateProfileOverview(accessToken: String, requestType: Constants.RequestCategory) {
        
    }
    
    /*
 
    func updateProfile(accountInformation: AccountInformation?, financialInformation: FinancialInformation?, replenishmentInformation: ReplenishmentInformation?, personalInformation: PersonalInformation?, failureMessage: String?, route: Route?, requestType: Constants.RequestCategory) {
        let request = ProfileModel.Request(accountInformation: AccountInformation?, financialInformation: FinancialInformation?, replenishmentInformation: ReplenishmentInformation?, personalInformation: PersonalInformation?, failureMessage: String?, route: Route?)
        
        if let responseHandler = presenter {
            let interfaceObj = loginUsecaseProvider.provideLoginUsecase(requestType: requestType, handler: responseHandler)
            interfaceObj.login(request: request)
        }
    }
    
    func getProfileOverview(accessToken: String, requestType: Constants.RequestCategory) {
        
        if let responseHandler = presenter {
            let interfaceObj = userProfileUsecaseProvider.provideProfileOverviewUsecase(requestType: requestType, handler: responseHandler)
            interfaceObj.getProfileOverview(accessToken: accessToken)
        }
    }
     
     */
}
