//
//  EditProfilePresenter.swift
//  CMAA
//
//  Created by Vivek, Amirapu on 22/08/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
class EditProfilePresenter {
    var viewController: IEditProfileViewable?
}
