//
//  LoginInteractor.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform

extension LoginInteractor: ILoginInteractable {
    func login(username: String, password: String, requestType: Constants.RequestCategory) {
        var request = LoginModel.Request(userName:username, password:password)
        
        if let responseHandler = presenter {
            let interfaceObj = loginUsecaseProvider.provideLoginUsecase(requestType: requestType, handler: responseHandler)
            interfaceObj.login(request: request)
        }
    }
    
    func getProfileOverview(accessToken: String, requestType: Constants.RequestCategory) {
        
    }

}
