//
//  LoginViewController.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform
import MBProgressHUD

extension LoginViewController: ILoginViewable {
    func loginSuccess(viewModel: LoginModel.PresentionModel) {
//        progressActivity.stopAnimating()

        if rememberMe.isOn {

            self.saveCredentials()
        }
        
        MBProgressHUD.hide(for: self.view, animated: true)
        
//        router?.perform(viewModel: viewModel)
    }
    func loginFailed(viewModel: LoginModel.PresentionModel) {
//        progressActivity.stopAnimating()
//        router?.perform(viewModel: viewModel)
        MBProgressHUD.hide(for: self.view, animated: true)
    }
    func userProfileSuccess(viewModel: ProfileModel.PresentionModel) {
        router?.perform(viewModel: viewModel)
    }
    func userProfileFailed(viewModel: ProfileModel.PresentionModel) {
        router?.perform(viewModel: viewModel)
    }
}
