//
//  LoginModels.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
public enum LoginModel {
    public struct Request: Codable {
        public init() {
        }
        public var userName: String?
        public var password: String?
        public var grantType: String?
        public var clientId: String?
        public var clientSecret: String?
        public var agencyID: String?
        public var loginType: String?

        public init(userName: String, password: String) {
            self.userName = userName
            self.password = password
            self.grantType = "password"
            self.clientId = "NJ_EZ_Pass"
            self.clientSecret = "N4pBHuCUgw8D2BdZtSMX2jexxw3tp7"
            self.agencyID = "1"
            self.loginType = "username"
        }
    }
    public struct Response: Codable {
        public init(accessToken: String, tokenType: String, expiresIn: Int, scope: String, agencyID: Int, brokerID: Int, firstName: String, permission: String, lastName: String, jti: String, failureMessage: String , route: Route?) {
            self.access_token = accessToken
            self.token_type = tokenType
            self.expires_in = expiresIn
            self.AgencyId = agencyID
            self.BrokerId = brokerID
            self.FirstName = firstName
            self.Permission = permission
            self.LastName = lastName
            self.jti = jti
            self.failureMessage = failureMessage
            self.route = route
        }
        public init() {
        }
        
        public var access_token, token_type, refresh_token: String?
        public var expires_in: Int?
        public var scope: String?
        public var AgencyId, BrokerId: Int?
        public var FirstName: String?
        public var Permission: String?
        public var LastName: String?
        public var jti: String?
        public var route: Route?
        public var failureMessage: String?
    }
    public struct PresentionModel {
        public var message: String?
        public var accessToken: String?
        public var route: Route?
        public init() {

        }
        public init(message: String?, accessToken: String?, route: Route?) {
            self.message = message
            self.accessToken = accessToken
            self.route = route
        }
    }
}
