//
//  LoginViewController.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform
import Apollo_iOS
import MBProgressHUD

class LoginViewController: UIViewController {
    
    var interactor: ILoginInteractable?
    var router: IRouter?
    @IBOutlet weak var txtUserID: ApolloTextInputField!
    @IBOutlet weak var txtPassword: ApolloTextInputField!
    @IBOutlet weak var progressActivity: UIActivityIndicatorView!
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    // MARK: Setup
    private func setup() {
        let configurator = LoginConfigurator()
        configurator.build(viewController: self)
        interactor = configurator.interactor
        router = configurator.router
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: false)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
    }
    @IBAction func backTapped(_ sender: Any) {
        self.navigationController?.popToRootViewController(animated: true)
    }
    
    @IBOutlet weak var biometricAuthBtn: UIButton!
    
    // MARK: IBActions
    @IBAction func loginClicked(_ sender: Any) {
        self.view.endEditing(true)
        self.resignFirstResponder()
        doLogin()
    }
    
    func doLogin() {
        if let username = txtUserID.text, let password = txtPassword.text {
//            self.progressActivity.startAnimating()
            MBProgressHUD.showAdded(to: self.view, animated: true)
            interactor?.login(username: username, password: password, requestType: .remote)
            
        } else {
            DialogUtils.shared.displayDialog(title: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.appName), message: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.invalidUserDetails), btnTitle: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.ok), vc: self, accessibilityIdentifier: AppStringKeys.invalidUserDetails)
        }
    }
    
    @IBAction func forgotPassClicked(_ sender: Any) {
    }
    
    @IBAction func biometricAuthBtnClicked(_ sender: Any) {
    }
}
