//
//  LoginViewController.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform
import Apollo_iOS
import MBProgressHUD
import KeychainAccess

class LoginViewController: UIViewController {
    
    var interactor: ILoginInteractable?
    var router: IRouter?
    @IBOutlet weak var txtUserID: ApolloTextInputField!
    @IBOutlet weak var txtPassword: ApolloTextInputField!
        {
        didSet
        {
            txtPassword.validationType = .password
        }
    }
    @IBOutlet weak var loginButton: UIButton!

    @IBOutlet weak var rememberMe: UISwitch!
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let configurator = LoginConfigurator()
        configurator.build(viewController: self)
        interactor = configurator.interactor
        router = configurator.router
    }
    
    private func fillCredentials() {
        print(#function)
        let keychain = Keychain(service: "com.conduent.NJEZPass")
        
        DispatchQueue.global().async {
            
            do {
                if let userId = try keychain.authenticationPrompt("Authenticate to login to server").get("userId") {
                    self.txtUserID.text = userId
                }
            }
            catch let error {
                print(error)
            }
            
            do {
                if let password = try keychain.authenticationPrompt("Authenticate to login to server").get("password") {
                    self.txtPassword.text = password
                }
            }
            catch let error {
                print(error)
            }
        }
        
        validateInput()
    }
    
    // MARK: ViewController lifecycle
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        fillCredentials()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: false)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        txtUserID.delegate = self
        txtPassword.delegate = self
        loginButton.isEnabled = false
        hideKeyboardWhenTap()
        toggleLoginButtonColor()
    }
    
    @IBAction func backTapped(_ sender: Any) {
        self.navigationController?.popToRootViewController(animated: true)
    }
    
    @IBOutlet weak var biometricAuthBtn: UIButton!
    
    // MARK: IBActions
    @IBAction func loginClicked(_ sender: Any) {
        self.view.endEditing(true)
        self.resignFirstResponder()
        doLogin()
    }
    
    func doLogin() {
        if let username = txtUserID.text, let password = txtPassword.text {
            
            //online login flow
//            MBProgressHUD.showAdded(to: self.view, animated: true)
//            interactor?.login(username: username, password: password, requestType: .remote)
            
            //direct login flow in case of api error
            var viewModel = ProfileModel.PresentionModel()
            viewModel.route = Route(id: AppStringKeys.loginSuccess, path: AppUIElementKeys.deviceVerification, nextURL: "", navigation: NavigationInfo.push)

            router?.perform(viewModel: viewModel)
            //saveCredentials()
            
        } else {
            DialogUtils.shared.displayDialog(title: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.appName), message: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.invalidUserDetails), btnTitle: Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.ok), vc: self, accessibilityIdentifier: AppStringKeys.invalidUserDetails)
        }
    }
    
    @IBAction func forgotPassClicked(_ sender: Any) {
    }
    
    @IBAction func biometricAuthBtnClicked(_ sender: Any) {
    }
    
    private func validateInput() {

        loginButton.isEnabled = false
        
        if let userName = txtUserID.text, let password = txtPassword.text, userName.count > 0, password.count > 0 {
            loginButton.isEnabled = true
        }

        toggleLoginButtonColor()
    }
    
    func toggleLoginButtonColor() {
        if loginButton.isEnabled {
            loginButton.backgroundColor = #colorLiteral(red: 0.4641762972, green: 0.2112366259, blue: 0.5424402356, alpha: 1)
        } else {
            loginButton.backgroundColor = #colorLiteral(red: 0.4489307404, green: 0.09403731674, blue: 0.5118483901, alpha: 0.5)
        }
    }
    
    func hideKeyboardWhenTap() {
        
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(LoginViewController.dismissKeyboard))
        
        tap.cancelsTouchesInView = false
        
        view.addGestureRecognizer(tap)
        
    }
    
    @objc func dismissKeyboard() {
        
        view.endEditing(true)
        
    }
    
    public func saveCredentials() {
        print(#function)
        let keychain = Keychain(service: "com.conduent.NJEZPass")
        
        do {
            try keychain.set(txtUserID.text!, key: "userId")
        }
        catch let error {
            print(error)
        }
        
        do {
            try keychain.set(txtPassword.text!, key: "password")
        }
        catch let error {
            print(error)
        }
    }
}

extension LoginViewController: ApolloTextInputFieldDelegate {
    
    func lawTextFieldDidBeginEditing(textField: ApolloTextInputField) {
        
    }
    
    func lawTextFieldDidEndEditing(textField: ApolloTextInputField) {
        
        validateInput()
    }
    
    func lawTextFieldDidChange(textField: ApolloTextInputField) {
    }
    
    func lawShouldChangeCharactersIn(_ textField: ApolloTextInputField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        
        return true
    }
    
    func lawTextFieldShouldReturn(_ textField: ApolloTextInputField) -> Bool {
        return true
    }
    
}
