//
//  LoginInteractor.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
import Platform

protocol ILoginInteractable {
    func login(username: String, password: String, requestType: Constants.RequestCategory)
    func getProfileOverview(action: String, requestType: Constants.RequestCategory)
}

class LoginInteractor {
    var presenter: IResponseHandler?
    var loginUsecaseProvider = LoginUsecaseProvider()
    var userProfileUsecaseProvider = UserProfileUsecaseProvider()
}

extension LoginInteractor: ILoginInteractable {
    func login(username: String, password: String, requestType: Constants.RequestCategory) {
        
//        verificationToken=TEST123|1.0|TEST|1.0|ACSInrixTrafficApp
        
        let token: String = APIConstants.DefaultParams.vendorID + "|" + APIConstants.DefaultParams.appVersion + "|" + UIDevice.modelName + "|" + APIConstants.DefaultParams.systemVersion + "|" + APIConstants.DefaultParams.token
        
        let verificationToken: String = token.sha256().lowercased()
        
        
        let request = LoginModel.Request(action: APIConstants.ServiceNames.loginUser, loginType: username, password: password, vendorId: APIConstants.DefaultParams.vendorID, model: UIDevice.modelName, systemVersion: UIDevice.current.systemVersion, appVersion: APIConstants.DefaultParams.appVersion, verificationToken: verificationToken)
        
        if let responseHandler = presenter {
            let interfaceObj = loginUsecaseProvider.provideLoginUsecase(requestType: requestType, handler: responseHandler)
            interfaceObj.login(request: request)
        }
    }
    
    func getProfileOverview(action: String, requestType: Constants.RequestCategory) {
        
        if let responseHandler = presenter {
            let interfaceObj = userProfileUsecaseProvider.provideProfileOverviewUsecase(requestType: requestType, handler: responseHandler)
            interfaceObj.getProfileOverview(action: action)
        }
    }
    
}
