//
//  LoginPresenter.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
class LoginPresenter {
    var viewController: ILoginViewable?
}

extension LoginPresenter: IResponseHandler {
    
    func onSuccess<T>(response: T) {
        print("onSucess: ", response)
        if let responseModel = response as? AuthorizeModel.Response {
            var viewModel = AuthorizeModel.PresentionModel()
            if let msg = responseModel.failureMessage {
                viewModel.message = msg
                viewModel.serviceId = ""
                viewController?.loginFailed(viewModel: viewModel)
            } else {
                
                CMUtility.firstTimeLogin = responseModel.firstTimeLogin
                CMUtility.suggestedAmount = responseModel.suggestedAmount
                CMUtility.nixieFlag = responseModel.nixieFlag
                
                viewModel.route = Route(id: AppStringKeys.loginSuccess, path: AppUIElementKeys.home, nextURL: "", navigation: NavigationInfo.push)
                viewController?.loginSuccess(viewModel: viewModel)
            }
        } else if let responseModel = response as? ProfileModel.Response {
            var viewModel = ProfileModel.PresentionModel()
            if let accountDetail = responseModel.accountDetail {
                
                viewModel.accountDetail = accountDetail
                viewModel.route = Route(id: AppStringKeys.loginSuccess, path: AppUIElementKeys.home, nextURL: "", navigation: NavigationInfo.push)
                
                let appDelegate = UIApplication.shared.delegate as? AppDelegate
                
                appDelegate?.detailInfo = viewModel.accountDetail
                
                viewController?.userProfileSuccess(viewModel: viewModel)
            } else {
                viewModel.message = responseModel.message
                viewController?.userProfileFailed(viewModel: viewModel)
            }
            print(responseModel)
        }
        else if let responseModel = response as? DynamicCacheModel.Response {
            
            CMUtility.dynamicPageLoad = responseModel.dynamicPageLoad
            viewController?.loadDynamicDataSuccess()
        }
    }
    
    func onError(err: APIError) {
        print("onError: ", err)
        var viewModel = AuthorizeModel.PresentionModel()
        viewModel.message = Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.loginFailure)
        viewModel.serviceId = ""
        viewController?.loginFailed(viewModel: viewModel)
    }
}
