//
//  LandingInteractor.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 12/08/19.
//  Copyright (c) 2019 Conduent. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingBusinessLogic
{
  func doSomething(request: Landing.Something.Request)
}

protocol LandingDataStore
{
  //var name: String { get set }
}

class LandingInteractor: LandingBusinessLogic, LandingDataStore
{
  var presenter: LandingPresentationLogic?
  var worker: LandingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Landing.Something.Request)
  {
    worker = LandingWorker()
    worker?.doSomeWork()
    
    let response = Landing.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
