//
//  LandingPresenter.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 12/08/19.
//  Copyright (c) 2019 Conduent. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPresentationLogic
{
  func presentSomething(response: Landing.Something.Response)
}

class LandingPresenter: LandingPresentationLogic
{
  weak var viewController: LandingDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Landing.Something.Response)
  {
    let viewModel = Landing.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
