//
//  LandingWorker.swift
//  NJEZPass
//
//  Created by Anshu Sharma on 12/08/19.
//  Copyright (c) 2019 Conduent. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LandingWorker
{
  func doSomeWork()
  {
  }
}
