//
//  LoginPresenter.swift
//  CMAA
//
//  Created by Latha, Sowjanya on 15/04/19.
//  Copyright (c) 2019 cnd. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Entities
import Domain
extension LoginPresenter: IResponseHandler {
    func onSuccess<T>(response: T) {
        print("onSucess: ", response)
        if let responseModel = response as? LoginModel.Response {
            var viewModel = LoginModel.PresentionModel()
            if let msg = responseModel.failureMessage {
                viewModel.message = msg
                viewModel.accessToken = ""
                viewController?.loginFailed(viewModel: viewModel)
            } else {
                viewModel.message = responseModel.access_token ?? "" + Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.loginSuccess)
                viewModel.accessToken = responseModel.access_token
                viewModel.route = Route(id: AppStringKeys.loginSuccess, path: AppUIElementKeys.home, nextURL: "", navigation: NavigationInfo.push)
                viewController?.loginSuccess(viewModel: viewModel)
            }
        }
    }

    func onError(err: APIError) {
        print("onError: ", err)
        var viewModel = LoginModel.PresentionModel()
        viewModel.message = Localizer.sharedInstance.localizedStringForKey(key: AppStringKeys.loginFailure)
        viewModel.accessToken = ""
        viewController?.loginSuccess(viewModel: viewModel)
    }

}
